### ISSUE TITLE
Works with S 9080 base+

### ISSUE THREAD

**Issue by tim-kiefer** [exico91/SommerESP#3]
This is a pretty cool project! Thanks for all the work that went into it.

I can confirm that it also works with die base+ series. I just installed two and am happy with the result. Unlike the pro, the base has no wall-mounted unit. Instead, the two modules are installed in the ceiling-mounted unit. And there is no need to re-attach a keypad cable (because there is no keypad). Otherwise, it is just the same board.

Cheers
Tim

**Comment by exico91** [comment]
Happy to know that! Perchance do you know your specific model? Ill just add it to the compatibility table
